### ISSUE TITLE
Total Bulletins Sent

### ISSUE THREAD

**Issue by omerbensaadon** [uscensusbureau/granicus#14]
![Bulletins_Sent](https://user-images.githubusercontent.com/16281246/55740336-de6da580-59f8-11e9-925f-786194d6e398.png)

**API Calls Used**
`/api/v2/accounts/{account_id}/reports/bulletins/summary`

**Data Needed:**
- (a) `bulletins_sent` between the user-defined `start_date` and `end_date` 
- (b) `bulletins_sent` the week before the user-defined `start_date and `end_date`
- (c) `bulletins_sent` 2 weeks before the user-defined `start_date` and `end_date`

- % Difference between (a) & (b)
- % Difference between (a) & (c)

**Comment by loganpowell** [comment]
Got it
![granicus-#14](https://user-images.githubusercontent.com/3408191/55981198-43790380-5c64-11e9-962d-b53a3c2224ad.PNG)
