### ISSUE TITLE
Delivery Rate

### ISSUE THREAD

**Issue by omerbensaadon** [uscensusbureau/granicus#17]
![Delivery_Rate](https://user-images.githubusercontent.com/16281246/55740395-ffce9180-59f8-11e9-810a-c0a3c8562d22.png)

**API Calls Used**
`/api/v2/accounts/{account_id}/reports/bulletins/summary`

**Data Needed:**
- (a) `total_delivered`÷`total_recipients` between the user-defined `start_date` and `end_date` (which we are assuming, unless told otherwise, will be a week. 
- (b) `total_delivered`÷`total_recipients` week before the user-defined `start_date` and `end_date`
- (c) `total_delivered`÷`total_recipients` 2 weeks before the user-defined `start_date` and `end_date` 

- % Difference b/w (a) & (b)
- % Difference b/w (a) & (c)

**Comment by loganpowell** [comment]
This is done
