### ISSUE TITLE
Total Subscribers

### ISSUE THREAD

**Issue by omerbensaadon** [uscensusbureau/granicus#20]
![TotalSubscribers](https://user-images.githubusercontent.com/16281246/55638832-1fb24b00-5796-11e9-8186-ca3c61b7e2da.png)

**API Calls Used**
`/api/v2/accounts/{account_id}/reports/subscriber_activity/summary`

**Data Needed:**
- (a) `total_subscribers` between the user-defined `start_date` and `end_date` (which we are assuming, unless told otherwise, will be a week. 
- (b) `total_subscribers` week before the user-defined `start_date` and `end_date`
- (c) `total_subscribers` 2 weeks before the user-defined `start_date` and `end_date` 

- % Difference b/w (a) & (b)
- % Difference b/w (a) & (c)

**Comment by loganpowell** [comment]
Again, not sure why I need to do anything here
