### ISSUE TITLE
New Subscribers

### ISSUE THREAD

**Issue by omerbensaadon** [uscensusbureau/granicus#21]
![New Subscribers](https://user-images.githubusercontent.com/16281246/55639646-dfec6300-5797-11e9-8467-c3be7d580fb6.png)

**API Calls Used**
`/api/v2/accounts/{account_id}/reports/subscriber_activity/summary`

**Data Needed:**
>`new_subscribers` = `SUM(direct_subscribers + overlay_subscribers + upload_subscribers + network_subscribers)`

- (a) `new_subscribers` between the user-defined `start_date` and `end_date` (which we are assuming, unless told otherwise, will be a week. 
- (b) `new_subscribers` week before the user-defined `start_date` and `end_date`
- (c) `new_subscribers` 2 weeks before the user-defined `start_date` and `end_date` 

- % Difference b/w (a) & (b)
- % Difference b/w (a) & (c)

**Comment by loganpowell** [comment]
This is done, but with one caveat, there doesn't exist a `network_subscribers` property in this response, but there is an `all_network_subscribers` property, which I used instead. If this isn't the right property it's easy to change. Moving to done.
