### ISSUE TITLE
New Overlay Subscribers

### ISSUE THREAD

**Issue by omerbensaadon** [uscensusbureau/granicus#22]
![Overlay Subscribers](https://user-images.githubusercontent.com/16281246/55639622-d105b080-5797-11e9-86f0-5143e22efb24.png)

**API Calls Used**
`/api/v2/accounts/{account_id}/reports/subscriber_activity/summary`

**Data Needed:**

- (a) `overlay_subscribers` between the user-defined `start_date` and `end_date` (which we are assuming, unless told otherwise, will be a week. 
- (b) `overlay_subscribers` week before the user-defined `start_date` and `end_date`
- (c) `overlay_subscribers` 2 weeks before the user-defined `start_date` and `end_date` 

- % Difference b/w (a) & (b)
- % Difference b/w (a) & (c)

**Comment by loganpowell** [comment]
Not sure I need to do anything here... `overlay_subscribers` is already in the "Subscribers Table".
