### ISSUE TITLE
Click Rate

### ISSUE THREAD

**Issue by omerbensaadon** [uscensusbureau/granicus#25]
![Click_Rate](https://user-images.githubusercontent.com/16281246/55741361-137af780-59fb-11e9-8a8e-cc5f2f702c91.png)

**API Calls Used**
`/api/v2/accounts/{account_id}/reports/bulletins/summary`

**Data Needed:**
- (a) `clicks_count` ÷`total_delivered`  between the user-defined `start_date` and `end_date` (which we are assuming, unless told otherwise, will be a week. 
- (b) `clicks_count` ÷`total_delivered` week before the user-defined `start_date` and `end_date`
- (c) `clicks_count` ÷`total_delivered` 2 weeks before the user-defined `start_date` and `end_date` 

- % Difference b/w (a) & (b)
- % Difference b/w (a) & (c)

**Comment by omerbensaadon** [comment]
To be calculated in Tableau

**Comment by loganpowell** [comment]
De-assigning myself this since this will be handled in Tableau

**Comment by loganpowell** [comment]
This is done
