### ISSUE TITLE
Deleted Subscribers

### ISSUE THREAD

**Issue by omerbensaadon** [uscensusbureau/granicus#26]
![Deleted_Subscribers](https://user-images.githubusercontent.com/16281246/55741583-9f8d1f00-59fb-11e9-8045-bc2bec1fd07a.png)

**API Calls Used**
`/api/v2/accounts/{account_id}/reports/subscriber_activity/summary`

**Data Needed:**
- (a) `deleted_subscribers` between the user-defined `start_date` and `end_date` (which we are assuming, unless told otherwise, will be a week. 
- (b) `deleted_subscribers` week before the user-defined `start_date` and `end_date`
- (c) `deleted_subscribers` 2 weeks before the user-defined `start_date` and `end_date` 

- % Difference b/w (a) & (b)
- % Difference b/w (a) & (c)

**Comment by loganpowell** [comment]
Also, don't know why this can't be done in tableau.
