### ISSUE TITLE
Unsubscribe Rate

### ISSUE THREAD

**Issue by omerbensaadon** [uscensusbureau/granicus#27]
![Unsubscribe_Rate](https://user-images.githubusercontent.com/16281246/55742062-c7c94d80-59fc-11e9-85b9-5a739d39afef.png)

**API Calls Used**
(1) `/api/v2/accounts/{account_id}/reports/subscriber_activity/summary`
(2) ` /api/v2/accounts/{account_id}/reports/bulletins/summary`

**Data Needed:**
- (a) (1) `deleted_subscribers` ÷ (2) `total_delivered` between the user-defined `start_date` and `end_date` (which we are assuming, unless told otherwise, will be a week)
- (b) (1) `deleted_subscribers` ÷ (2) `total_delivered` week before the user-defined `start_date` and `end_date`
- (c) (1) `deleted_subscribers` ÷ (2) `total_delivered` 2 weeks before the user-defined `start_date` and `end_date`

**Comment by loganpowell** [comment]
There is no `total_delivered` property in the summary payload. Here is an example payload from this endpoint:

```js
{
all_network_subscribers: 3299
all_network_subscriptions: 24077
deleted_subscribers: 3158
deleted_subscriptions: 23709
direct_subscribers: 1517
direct_subscriptions: 34216
net_subscribers: 8973
net_subscriptions: 44878
other_subscribers: 0
other_subscriptions: 0
overlay_subscribers: 3140
overlay_subscriptions: 3421
total_subscribers: 1022734
total_subscriptions: 4460116
upload_subscribers: 4175
upload_subscriptions: 6873
_links:
find: {templated: true, href: "/api/v2/accounts/11723/reports/subscriber_activity…mmary?start_date={start_date}&end_date={end_date}"}
self: {href: "/api/v2/accounts/11723/reports/subscriber_activity/summary?end_date=2019-04-08&start_date=2019-04-01"}
}
```

**Comment by omerbensaadon** [comment]
This was a silly mistake. 

Updated the issue above to reflect the `total_subscribers` not `total_delivered` as originally written.

**Comment by loganpowell** [comment]
This is done, but the numbers are super tiny (e.g., 0.0012) and - perhaps more importantly - not based on a periodic performance window. Not sure if `total_subscribers` should be the denominator, perhaps it should be something akin to how granicus calculates net subscribers, which we found out from Sultan is this:
`direct_subscribers` + `overlay_subscribers` + `upload_subscribers` + `all_network_subscribers` + `other_subscribers` (subtotal)
-
`deleted_subscribers` 
= 
`net_subscribers`

perhaps we should use the subtotal or just `net_subscribers` as the denominator... thoughts?

**Comment by ACalaCensus** [comment]
Sorry @loganpowell and @omerbensaadon I think you guys are not quite getting at what I am looking for. This metric requires us to look at engagement data and subscriber data to produce a rough unsubscribe rate for a period of time. We're doing this because I don't think that we have programmatic access via the API to the unsibscribe rate for each message sent and I need something to serve as a proxy metric.

I want to be able to measure the total number of messages delivered in the past period of performance (April 17 - April 23). According to the Bulletin Analytics Report, that number was 2,606,964.
Then we need to divide that number by the number of deleted subscribers for the past period of performance (April 17 - April 23). According to the Subscriber Activity Report, that number was 2,663.
So taking these two numbers together we get 2,663 / 2,606,964 = an unsubscribe rate of 0.10%.

**Comment by loganpowell** [comment]
So, the `deleted_subscribers` ÷ `total_subscribers` is correct. Then, this is done.

**Comment by ACalaCensus** [comment]
Let’s discuss this afternoon.

Anthony Calabrese, Digital Marketing Lead
CLMSO, Communications Directorate
U.S. Census Bureau
Call: 301-763-9459<tel:301-763-9459> | Text Me: 202-770-9997<tel:202-770-9997>
census.gov<https://www.census.gov/> | @uscensusbureau

On Apr 30, 2019, at 8:41 AM, Logan Powell <notifications@github.com<mailto:notifications@github.com>> wrote:


So, the deleted_subscribers ÷ total_subscribers is correct. Then, this is done.

**Comment by omerbensaadon** [comment]
Updated to reflect Anthony's comment. 

Updated size to `M`.

Will finalize requirement in today's meeting.

**Comment by omerbensaadon** [comment]
@ACalaCensus can you review the updated requirement above and approve or comment? 

We pushed the meeting yesterday so Logan and I could get our stuff together before we on-board Tableau folks.

**Comment by loganpowell** [comment]
Are we good to go with this?

**Comment by omerbensaadon** [comment]
Good to go as in good to implement? Or good to go as in this is done? 

We are good to go in terms of implementing, spoke with Anthony in person yesterday

**Comment by loganpowell** [comment]
Cool. Good to go as to implement...

**Comment by loganpowell** [comment]
Done
