### ISSUE TITLE
Create "Today's Date" function in JS

### ISSUE THREAD

**Issue by omerbensaadon** [uscensusbureau/granicus#3]
Need to create a Today's Date function in JS formatted as "YYYY-MM-DD" so we can plug it into any "end_date" variable in the API calls if we want data up unto today.

**Comment by omerbensaadon** [comment]
@loganpowell we're going to need this for a bunch of our calls. 

Do you mind doing this and then letting me know at which piece of the infrastructure this call returns?

**Comment by loganpowell** [comment]
This is done:

https://github.com/uscensusbureau/granicus/blob/master/src/granicus.js#L9

**Comment by RyanDolan** [comment]
Maybe review this and use today's date?
