### ISSUE TITLE
Issues with multiple API calls

### ISSUE THREAD

**Issue by loganpowell** [uscensusbureau/granicus#35]
I'm struggling to make the multiple API calls required to get the periodic differences for the Weekly report. 

Here are my current blockers:

- [] Tableau's internal browser looks like a very very old (like IE 8-level old) fossil of a browser. I'm trying to use Babel to transpile more modern JavaScript into ES5 code, which seems to be working, but it's very difficult to debug due to the following issues:
- [] Tableau has multiple [phases](), which need to communicate to each other via a `connectionData` global variable. That's not horrible in and of itself, but when this global variable changes hands isn't apparent and logging using `tableau.log` isn't getting me anywhere as of yet
- [] Logging: the `tableau.log` functionality isn't helping me right now. I'm struggling to find a way to see what data is being passed between phases and what I'm working with in each phase.

I'm giving up for the day, mostly because my sight is blurring from staring angrily at my monitors for the last 11 hours.

**Comment by omerbensaadon** [comment]
Alright man, let’s circle back tomorrow and see if we can’t come up with a
solution.

Thanks for your effort on this today, appreciate your commitment to staying
on schedule.

Best,
Omer Bensaadon

**Comment by loganpowell** [comment]
If you'd like to work with some dummy data so I'm not blocking you @omerbensaadon, the resulting table should look like this:

| Name of Metric | This Week | Previous Week | Three Weeks Ago |
| --- | --- | --- | --- |
| Deleted subscribers | 1000 | 299 | 1291|

**Comment by loganpowell** [comment]
They're all going to be counts

**Comment by omerbensaadon** [comment]
https://tableau.github.io/webdataconnector/docs/wdc_debugging

https://tableau.github.io/webdataconnector/docs/wdc_faq

https://community.tableau.com/thread/260189
^ This guy solved a similar problem by using promises, which I think you mentioned...

**Comment by omerbensaadon** [comment]
https://www.youtube.com/watch?v=RIVIh-btZh4&index=5&list=PL_qx68DwhYA8E80s9JOnQzzPkX7sWK-pl

**Comment by loganpowell** [comment]
Got it working... for now

**Comment by omerbensaadon** [comment]
How?!
