### ISSUE TITLE
Pull Total Subscribers

### ISSUE THREAD

**Issue by omerbensaadon** [uscensusbureau/granicus#4]
We need to pull the total number of subscribers on our list. 

API Call: 
List Subscriber Activity Reports
GET - /api/v2/accounts/{account_id}/reports/subscriber_activity/summary

Parameters Needed:
**NOTE Change in parameters** _Opting for "days = 1" because the total number of subscribers stays the same, and I have a feeling that pulling a shorter amount of time will mean less latency_
days: 1
end_date: Today

Return Data Used:

total_subscribers

Segmentation Data Needed:

- [x] 1. All Time Test

Need to check which of these numbers we're going to use.

**Comment by loganpowell** [comment]
Got the first test up and running. Just use this as your WDC in Tableau:

https://loganpowell.github.io/granicus/

**Comment by omerbensaadon** [comment]
See above change in requirements.

**Comment by omerbensaadon** [comment]
I'm closing this, we don't need the Javascript test here. 

It turns out that, in this instance, when you only use the `days` parameter, the end_date defaults to `today`

Example call:
`https://api.govdelivery.com/api/v2/accounts/11723/reports/subscriber_activity/summary?days=1`

**Comment by omerbensaadon** [comment]
<img width="397" alt="Screen Shot 2019-04-01 at 4 53 02 PM" src="https://user-images.githubusercontent.com/16281246/55358949-aae1c700-549e-11e9-935f-a846f34c03ec.png">

This is the "image" deliverable we're looking for. Going to reopen this since we haven't really cleared any prototypes with Anthony.

**Comment by loganpowell** [comment]
This is ready. The new WDC lives at: https://uscensusbureau.github.io/granicus/

**Comment by loganpowell** [comment]
![all_time_subscribers](https://user-images.githubusercontent.com/3408191/55481352-36b73880-55f0-11e9-91a5-045e5e64f79f.PNG)
