### ISSUE TITLE
Increment end_date by 1 in the Bulletins Table for "This Week" Metrics

### ISSUE THREAD

**Issue by omerbensaadon** [uscensusbureau/granicus#59]
### API Bug Work-Around

The screenshot shown below is the data returned when the user enters `May 7 2019` as their preferred date. The backend API Call sets the `start_date` as `2019-04-30` and `end_date` as `2019-05-07`. 
<img width="641" alt="Screen Shot 2019-05-13 at 3 15 34 PM" src="https://user-images.githubusercontent.com/16281246/57720021-ff0bc980-764e-11e9-8d57-e9e95b09d623.png">

Now let's look at what is returned by the web-portal using these exact same dates:
<img width="767" alt="Screen Shot 2019-05-13 at 3 15 47 PM" src="https://user-images.githubusercontent.com/16281246/57719826-9290ca80-764e-11e9-8bea-88e509d82d29.png">

Different data... seems like the API is leaving a day out of the calculations. Let's try setting the `end_date` to one day after the user-selected date of `2019-05-07`

<img width="818" alt="Screen Shot 2019-05-14 at 1 47 44 PM" src="https://user-images.githubusercontent.com/16281246/57719973-e0a5ce00-764e-11e9-9335-5d2abf145c2b.png">

Now the data matches up with the web-portal! 

### Requirement
- [ ] Set the `end_date` in the API Call for `This Week`'s data in the `Bulletins Table` to +1 more than the user-defined date.
- [ ] QA To ensure this fixes the problem and the data matches the data shown in the web-portal. Use the dates 4/30 - 5/07 in the Web Portal. 

### API Calls Required
`/api/v2/accounts/{account_id}/reports/bulletins/summary`

**Comment by loganpowell** [comment]
this is done
