### ISSUE TITLE
Remove Engagement Rates from the Total Engagement + Subscribers Table

### ISSUE THREAD

**Issue by omerbensaadon** [uscensusbureau/granicus#61]
### Requirements
- [ ] Remove Engagement Rates from table
- [ ] Comment out Engagement Rate code in backend, include explanation for removal
`Engagement rate removed since Granicus API cannot return historical data down to the day via the API`
- [ ] Convert items in tables from floats to integers

**Comment by omerbensaadon** [comment]
You're okay to start on this!

**Comment by loganpowell** [comment]
This is done. Please verify all's well.
