### ISSUE TITLE
Fix Bulletins Table

### ISSUE THREAD

**Issue by omerbensaadon** [uscensusbureau/granicus#64]
### Pseudocode

Pulls from end-point `/api/v2/accounts/{account_id}/reports/bulletins/summary`

Data Provided by User:  May 14 2019

`date` = May 14 2019

//Adjusting for Granicus bug detailed in #59 
`date` += 1

DataPull(end_date, days_before_end_date){
//**time_frame** = (end_date - days_before_end_date) -> end_date
//Pulls data from the specified time_frame
}

`end_date` = `date`

FirstWeekDataPull = DataPull(`end_date`, 7); 
//Calls API from dates May 8 - 15
//**Returns Data for dates May 8 - 14 because of #59 bug**

//Setting `end_date` to May 8
`end_date` = `date`-7

SecondWeekDataPull = DataPull(`end_date`, 7);
//Calls API from dates May 1-8
//**Returns Data for dates May 1 - 7 because of #59 bug**

//Setting `end_date` to May 1
`end_date` = `end_date` - 7
// OR `date` - 14

ThirdWeekDataPull = DataPull(`end_date`, 7);
//Calls API from dates April 24 - May 1
//**Returns Data for dates April 24-30 because of #59 bug**

**Comment by loganpowell** [comment]
Give it another check

**Comment by loganpowell** [comment]
Let's say we have date as
```
May 7 2019
```
here's what nudging the calls one day forward in time with a one day overlap gets us:

```
[ 'https://cors-e.herokuapp.com/https://api.govdelivery.com/api/v2/accounts/11723/reports/bulletins/summary?start_date=2019-05-01&end_date=2019-05-08', 
  'https://cors-e.herokuapp.com/https://api.govdelivery.com/api/v2/accounts/11723/reports/bulletins/summary?start_date=2019-04-24&end_date=2019-05-01', 
  'https://cors-e.herokuapp.com/https://api.govdelivery.com/api/v2/accounts/11723/reports/bulletins/summary?start_date=2019-04-17&end_date=2019-04-24' ]
```
What's wrong with this?

**Comment by omerbensaadon** [comment]
Those actually look like they should be fine... let me test again

**Comment by omerbensaadon** [comment]
EUREKA! 

Subscribers psuedocode coming soon...
